import { MaintenanceRequest } from '@/types';

export const mockMaintenanceRequests: MaintenanceRequest[] = [
  {
    id: '1',
    propertyId: '1',
    tenantId: '1',
    category: 'plumbing',
    description: 'Torneira da casa de banho com fuga de água',
    urgency: 'medium',
    status: 'in-progress',
    createdAt: '2024-12-20',
    updatedAt: '2024-12-22',
  },
  {
    id: '2',
    propertyId: '1',
    tenantId: '1',
    category: 'electrical',
    description: 'Tomada do quarto não funciona',
    urgency: 'low',
    status: 'pending',
    createdAt: '2024-12-18',
  },
  {
    id: '3',
    propertyId: '4',
    tenantId: '1',
    category: 'hvac',
    description: 'Ar condicionado faz barulho estranho',
    urgency: 'medium',
    status: 'completed',
    createdAt: '2024-12-10',
    updatedAt: '2024-12-15',
  },
  {
    id: '4',
    propertyId: '2',
    tenantId: '1',
    category: 'appliance',
    description: 'Máquina de lavar roupa avariada',
    urgency: 'high',
    status: 'pending',
    createdAt: '2024-12-24',
  },
  {
    id: '5',
    propertyId: '5',
    tenantId: '1',
    category: 'structural',
    description: 'Infiltração no teto da sala',
    urgency: 'high',
    status: 'in-progress',
    createdAt: '2024-12-15',
    updatedAt: '2024-12-20',
  },
];
