import { Property } from '@/types';

export const mockProperties: Property[] = [
  {
    id: '1',
    title: 'Apartamento Moderno em Chiado',
    address: 'Rua Garrett 45',
    city: 'Lisboa',
    type: 'apartment',
    bedrooms: 2,
    bathrooms: 1,
    area: 85,
    price: 1200,
    status: 'occupied',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    ],
    features: ['Varanda', 'Estacionamento', 'Elevador', 'Ar Condicionado'],
    description: 'Apartamento elegante no coração de Lisboa, com acabamentos de alta qualidade e vista para o rio Tejo. Localização privilegiada junto a restaurantes, lojas e transportes públicos.',
    ownerId: '2',
    tenantId: '1',
    createdAt: '2024-06-15',
  },
  {
    id: '2',
    title: 'T3 com Terraço em Foz',
    address: 'Avenida Brasil 234',
    city: 'Porto',
    type: 'apartment',
    bedrooms: 3,
    bathrooms: 2,
    area: 120,
    price: 1500,
    status: 'available',
    images: [
      'https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
    ],
    features: ['Terraço', 'Garagem', 'Lareira', 'Vista Mar'],
    description: 'Magnífico apartamento T3 na prestigiada zona da Foz do Douro. Terraço com 40m² e vista panorâmica para o oceano. Acabamentos premium e design contemporâneo.',
    ownerId: '2',
    createdAt: '2024-08-20',
  },
  {
    id: '3',
    title: 'Estúdio no Centro Histórico',
    address: 'Rua de Santa Maria 12',
    city: 'Sintra',
    type: 'studio',
    bedrooms: 0,
    bathrooms: 1,
    area: 45,
    price: 650,
    status: 'available',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    ],
    features: ['Mobilado', 'Internet Incluída', 'Cozinha Equipada'],
    description: 'Estúdio acolhedor no centro histórico de Sintra, totalmente mobilado e equipado. Ideal para jovens profissionais ou estudantes.',
    ownerId: '3',
    createdAt: '2024-09-10',
  },
  {
    id: '4',
    title: 'Moradia V4 com Piscina',
    address: 'Rua das Flores 78',
    city: 'Cascais',
    type: 'villa',
    bedrooms: 4,
    bathrooms: 3,
    area: 280,
    price: 3500,
    status: 'occupied',
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
    ],
    features: ['Piscina', 'Jardim', 'Garagem 2 Carros', 'Churrasqueira', 'Domótica'],
    description: 'Luxuosa moradia em Cascais com piscina privativa e jardim. Casa inteligente com sistema de domótica completo. Zona residencial tranquila a minutos da praia.',
    ownerId: '2',
    tenantId: '1',
    createdAt: '2024-03-05',
  },
  {
    id: '5',
    title: 'Loft Industrial em Alcântara',
    address: 'Rua Prior do Crato 88',
    city: 'Lisboa',
    type: 'apartment',
    bedrooms: 1,
    bathrooms: 1,
    area: 95,
    price: 1100,
    status: 'maintenance',
    images: [
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800',
    ],
    features: ['Tetos Altos', 'Open Space', 'Estacionamento'],
    description: 'Loft único em antiga fábrica renovada. Espaço amplo com pé direito de 4 metros e detalhes industriais originais preservados.',
    ownerId: '3',
    createdAt: '2024-07-22',
  },
  {
    id: '6',
    title: 'T2 Renovado em Baixa',
    address: 'Praça do Comércio 15',
    city: 'Lisboa',
    type: 'apartment',
    bedrooms: 2,
    bathrooms: 1,
    area: 75,
    price: 1350,
    status: 'available',
    images: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
    ],
    features: ['Renovado', 'Exposição Solar Sul', 'Cozinha Americana'],
    description: 'Apartamento totalmente renovado na icónica Praça do Comércio. Combina charme histórico com conforto moderno. Excelente luminosidade natural.',
    ownerId: '2',
    createdAt: '2024-10-01',
  },
];
